// To enable `#[allow(clippy::all)]`
//#![feature(tool_lints)]

/// Module containing functions to generate witnet's protocol messages
pub mod builders;

/// Module generated by flatbuffers compiler, containing flatbuffers protocol messages types
pub mod flatbuffers;

/// Module containing functions to cast witnet's protocol messages to flatbuffers and vice versa
pub mod serializers;

/// Module containing witnet's protocol messages types
pub mod types;
