# Sample Server Configuration File for Rust-Witnet
#
# When running the witnet executable without specifying any command line
# arguments, it will look for this file in three places, in the following
# order:
#
# -The working directory
# -The directory in which the executable resides
# -[user home]/.wit
#

#########################################
### SERVER CONFIGURATION              ###
#########################################

#Server connection details
[server]

#The chain type, which defines the genesis block. Can be:
#AutomatedTesting - For CI builds and instant blockchain creation
#UserTesting - For regular user testing
#Testnet1 - Testnet1 genesis block
#
chain_type = "UserTesting"

#The directory, relative to current, in which the witnet blockchain
#is stored
db_root = ".wit"

[server.p2p_config]
host = "0.0.0.0"
port = 11337

#########################################
### LOGGING CONFIGURATION             ###
#########################################

[logging]

# Whether to log to stdout
log_to_stdout = true

# Log level for stdout: Critical, Error, Warning, Info, Debug, Trace
stdout_log_level = "Debug"

# Whether to log to a file
log_to_file = true

# Log level for file: Critical, Error, Warning, Info, Debug, Trace
file_log_level = "Debug"

# Log file path
log_file_path = "wit.log"

# Whether to append to the log file (true), or replace it on every run (false)
log_file_append = true