[package]
name = "witnet_protected"
version = "0.3.2"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
workspace = ".."
description = "Sensitive byte buffers that are zeroed automatically when dropped"

[features]
with-serde = ["serde"]

[dependencies]
memzero = "0.1.0"
serde = { version = "1.0.104", optional = true }
