version: '3'

services:
  node:
    image: witnet/witnet-rust
    restart: unless-stopped
    command: ["latest", "node", "server"]
    ports:
      - "21337:21337"
    volumes:
      - "$HOME/.witnet:/.witnet:rw"
  node2:
    image: witnet/witnet-rust
    restart: unless-stopped
    command: ["latest", "node", "server"]
    ports:
      - "22337:21337"
    volumes:
      - "$HOME/.witnet2:/.witnet:rw"
  node3:
    image: witnet/witnet-rust
    restart: unless-stopped
    command: ["latest", "node", "server"]
    ports:
      - "23337:21337"
    volumes:
      - "$HOME/.witnet3:/.witnet:rw"
  node4:
    image: witnet/witnet-rust
    restart: unless-stopped
    command: ["latest", "node", "server"]
    ports:
      - "24337:21337"
    volumes:
      - "$HOME/.witnet4:/.witnet:rw"
  node5:
    image: witnet/witnet-rust
    restart: unless-stopped
    command: ["latest", "node", "server"]
    ports:
      - "25337:21337"
    volumes:
      - "$HOME/.witnet5:/.witnet:rw"
