[package]
name = "partial_struct"
version = "0.3.2"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
workspace = ".."
description = "Proc-macro that derives a partial struct with all fields wrapped in Option<T>"

[dependencies]
quote = "0.6.11"
syn = "0.15.26"

[dev-dependencies]
serde = { version = "1.0.88", features = ["derive"] }
syn = { version = "0.15.26", features = ["extra-traits"] }

[lib]
proc-macro = true
