[package]
name = "witnet_storage"
version = "0.3.2"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
workspace = ".."
description = "Key-value storage abstraction with an optional RocksDB backend for Witnet node state"

[dependencies]
anyhow = "1.0.98"
thiserror = "2.0.12"
rocksdb = { git = "https://github.com/rust-rocksdb/rust-rocksdb.git", rev = "7e7a1d594dd3960ad03a7006388640f90d17dae1", optional = true }

[features]
rocksdb-backend = ["rocksdb"]
